FROM httpd:2.4
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY httpd-ssl.conf /usr/local/apache2/conf/extra/httpd-ssl.conf
# COPY server.crt /usr/local/apache2/conf/server.crt
# COPY server.key /usr/local/apache2/conf/server.key
# COPY CAChains.crt /usr/local/apache2/conf/CAChains.crt
# COPY proxy-html.conf /usr/local/apache2/conf/extra/proxy-html.conf
